# -*- coding: utf-8 -*-
import json
import os
from datetime import datetime
import pytz

# --- Configuration ---
STATS_FILE_PATH = 'LiveTV/AniXLinks/stats.json'
README_FILE_PATH = 'README.md'
REPO_URL = 'AniketSainOp/AniXLinks'
AUTHOR_NAME = 'Aniket (aniket_aep)'
INSTAGRAM_URL = 'https://instagram.com/aniket_aep'
# ---------------------

# --- Load Statistics ---
try:
    with open(STATS_FILE_PATH, 'r', encoding='utf-8') as f:
        stats = json.load(f)
except FileNotFoundError:
    stats = {'total_channels': 0, 'total_groups': 0}

total_channels = stats.get('total_channels', 0)
total_groups = stats.get('total_groups', 0)
last_updated = datetime.now(pytz.timezone('Asia/Kolkata')).strftime('%d %B %Y, %I:%M %p IST')

# --- README Content Template ---
readme_content = f"""
<div align="center">

# AniXLinks IPTV Playlist Collector

**A high-performance, automated M3U playlist aggregator by {AUTHOR_NAME}**

[![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/{REPO_URL}/update.yml?style=for-the-badge&logo=githubactions&logoColor=white)](https://github.com/{REPO_URL}/actions) [![Last Commit](https://img.shields.io/github/last-commit/{REPO_URL}?style=for-the-badge&logo=git&logoColor=white)](https://github.com/{REPO_URL}/commits/main) [![License](https://img.shields.io/github/license/{REPO_URL}?style=for-the-badge)](https://github.com/{REPO_URL}/blob/main/LICENSE)

</div>

---

## Live Statistics

This project automatically scours the web for publicly available IPTV channel streams and compiles them into a single, convenient M3U playlist. The lists are updated **every 6 hours** to ensure the links are as fresh as possible.

| Total Channels | Total Groups | Last Updated |
| :---: | :---: | :---: |
| **{total_channels}** | **{total_groups}** | **{last_updated}** |

---

## Quick Access & Download

Use the following links to directly access the playlists. These links are automatically updated by the workflow.

- **M3U Playlist URL**: 
https://raw.githubusercontent.com/{REPO_URL}/main/LiveTV/AniXlinks/AniXLinks.m3u

- **JSON Playlist URL**: 
https://raw.githubusercontent.com/{REPO_URL}/main/LiveTV/AniXLinks/AniXLinks.json



## Disclaimer

This tool is provided for **educational purposes only**.

- The playlists generated by this script contain links to publicly available content on the internet.
- Users are solely responsible for ensuring they are not violating any copyright laws in their region by accessing this content.
- Please respect the terms of service of the original content providers. The author is not liable for any misuse of this tool.

---

<div align="center">
<p><em>This project is proudly developed and maintained by <a href="{INSTAGRAM_URL}">{AUTHOR_NAME}</a>.</em></p>
<p>Star the repository if you find it useful!</p>
</div>
"""

# --- Write the new README file ---
with open(README_FILE_PATH, 'w', encoding='utf-8') as f:
  f.write(readme_content)

print("[OK] README.md has been successfully updated.")
