# -*- coding: utf-8 -*-
import json
import os
from datetime import datetime
import pytz

stats_path = 'LiveTV/AniXLinks/stats.json'
readme_path = 'README.md'
repo_owner_and_name = 'aniketsainiop/AniXLinks'

# Load stats
if os.path.exists(stats_path):
    with open(stats_path, 'r', encoding='utf-8') as f:
        stats = json.load(f)
else:
    stats = {'total_channels': 0, 'total_groups': 0}

# Define README template
readme_template = <div align="center">

# 🎬 AniXLinks IPTV Playlist Links Collector With Json And m3u (Auto Update)

**A high-performance, automated M3U playlist & Json aggregator by Aniket (aniket_aep)**

[![GitHub Actions Workflow Status](https://img.shields.io/github/actions/workflow/status/AniketSainOp/AniXLinks/update.yml?style=for-the-badge&logo=githubactions&logoColor=white)](https://github.com/AniketSainOp/AniXLinks/actions) [![Last Commit](https://img.shields.io/github/last-commit/AniketSainOp/AniXLinks?style=for-the-badge&logo=git&logoColor=white)](https://github.com/AniketSainOp/AniXLinks/commits/main) [![License](https://img.shields.io/github/license/AniketSainOp/AniXLinks?style=for-the-badge)](https://github.com/AniketSainOp/AniXLinks/blob/main/LICENSE)

</div>

---

## 📊 Live Statistics

This project automatically scours the web for publicly available IPTV channel streams and compiles them into a single, convenient M3U playlist. The lists are updated **every 6 hours** to ensure the links are as fresh as possible.

| 📺 Total Channels | 📂 Total Groups | 🕐 Last Updated |
| :---: | :---: | :---: |
| **0** | **0** | **18 July 2025, 05:11 PM IST** |

---

## 🚀 Quick Access & Download

Use the following links to directly access the playlists.

- **M3U Playlist URL**: 
https://raw.githubusercontent.com/AniketSainOp/AniXLinks/main/LiveTV/AniXLinks/AniXLinks.m3u

- **JSON Playlist URL**: 
https://raw.githubusercontent.com/AniketSainOp/AniXLinks/main/LiveTV/AniXLinks/AniXLinks.json


## ⚠️ Disclaimer

This tool is provided for **educational purposes only**.

- The playlists generated by this script contain links to publicly available content on the internet.
- Users are solely responsible for ensuring they are not violating any copyright laws in their region by accessing this content.
- Please respect the terms of service of the original content providers. The author is not liable for any misuse of this tool.

---

<div align="center">
<p>Follow me on Instagram: <a href="https://instagram.com/aniket_aep">@aniket_aep</a></p>
</div>
